apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for PaaS-TA Container Platform Pipeline Inspection Api
name: paas-ta-container-platform-pipeline-inspection-api
type: application
version: "1.2"
