# Default values for paas-ta-container-platform-source-control-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: container-platform-source-control-ui
  namespace: ${NAMESPACE}

spec:
  replicas: 1

image:
  registry: ${REPOSITORY_URL}
  project: ${REPOSITORY_PROJECT_NAME}
  name: paas-ta-container-platform-source-control-ui
  tags: ${IMAGE_TAGS}
  pullPolicy: ${IMAGE_PULL_POLICY}
  secret: ${IMAGE_PULL_SECRET}

service:
  type: ${SERVICE_TYPE}
  protocol: ${SERVICE_PROTOCOL}
  port: 8094
  targetPort: 8094
  nodePort: 30094

env:
  cp:
    sourcecontrol:
      api: http://container-platform-source-control-api-service.${NAMESPACE}.svc.cluster.local:8091
  keycloak:
    url: http://${KEYCLOAK_URL}
    realm: ${KEYCLOAK_CP_REALM}
    client:
      id: ${KEYCLOAK_CP_CLIENT_ID}
      secret: ${KEYCLOAK_CP_CLIENT_SECRET}
      role: ${KEYCLOAK_CLUSTER_ADMIN_ROLE}

