apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.metadata.name }}-pv
  namespace: {{ .Values.metadata.namespace }}
spec:
  storageClassName: {{ .Values.persistent.storage.class }}
  accessModes:
    - {{ .Values.persistent.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistent.storage.size }}

