# Default values for paas-ta-container-platform-admin-service-broker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: container-platform-admin-service-broker
  namespace: ${CONTAINER_PLATFORM_PORTAL_NAMESPACE}

spec:
  replicas: 1

image:
  registry: ${REPOSITORY_URL}
  project: ${REPOSITORY_PROJECT_NAME}
  name: paas-ta-container-platform-admin-service-broker
  tags: ${IMAGE_TAGS}
  pullPolicy: ${IMAGE_PULL_POLICY}
  secret: ${IMAGE_PULL_SECRET}

service:
  type: ${SERVICE_TYPE}
  protocol: ${SERVICE_PROTOCOL}
  port: 3330
  targetPort: 3330
  nodePort: 32704

env:
  database:
    addr: "${DATABASE_URL}"
    user: "${DATABASE_USER_ID}"
    password: "${DATABASE_USER_PASSWORD}"
  k8s:
    api:
      server: "https://${K8S_MASTER_NODE_IP}:${K8S_API_SERVER_PORT}"
      token: "${K8S_AUTH_BEARER_TOKEN}"
  keycloak:
    url: "http://${KEYCLOAK_URL}"
    realm: "${KEYCLOAK_CP_REALM}"
    admin:
      username: "${KEYCLOAK_ADMIN_USERNAME}"
      password: "${KEYCLOAK_ADMIN_PASSWORD}"
  cp:
    common:
      api:
        url: "http://container-platform-common-api-service.${CONTAINER_PLATFORM_PORTAL_NAMESPACE}.svc.cluster.local:3334"
    api:
      url: "http://container-platform-api-service.${CONTAINER_PLATFORM_PORTAL_NAMESPACE}.svc.cluster.local:3333"
    portal:
      url: "http://${K8S_MASTER_NODE_IP}:32703"  # PaaS-TA Container Platform Web Admin Portal URI
    admin:
      org: "portal"
