# Default values for paas-ta-container-platform-pipeline-config-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: container-platform-pipeline-config-server
  namespace: ${NAMESPACE}

spec:
  replicas: 1

image:
  registry: ${REPOSITORY_URL}
  project: ${REPOSITORY_PROJECT_NAME}
  name: paas-ta-container-platform-pipeline-config-server
  tags: ${IMAGE_TAGS}
  pullPolicy: ${IMAGE_PULL_POLICY}
  secret: ${IMAGE_PULL_SECRET}

service:
  type: ${SERVICE_TYPE}
  protocol: ${SERVICE_PROTOCOL}
  port: 8080
  targetPort: 8080
  nodePort: 30088

env:
  database:
    url: ${DATABASE_URL}
    user:
      id: ${DATABASE_USER_ID}
      password: ${DATABASE_USER_PASSWORD}
