# Default values for paas-ta-container-platform-source-control-broker
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: container-platform-source-control-broker
  namespace: ${NAMESPACE}

spec:
  replicas: 1

image:
  registry: ${REPOSITORY_URL}
  project: ${REPOSITORY_PROJECT_NAME}
  name: paas-ta-container-platform-source-control-broker
  tags: ${IMAGE_TAGS}
  pullPolicy: ${IMAGE_PULL_POLICY}
  secret: ${IMAGE_PULL_SECRET}

service:
  type: ${SERVICE_TYPE}
  protocol: ${SERVICE_PROTOCOL}
  port: 8093
  targetPort: 8093
  nodePort: 30093

env:
  database:
    url: ${DATABASE_URL}
    user:
      id: ${DATABASE_USER_ID}
      password: ${DATABASE_USER_PASSWORD}
  cp:
    sourcecontrol:
      api:
        uri: http://container-platform-source-control-api-service.${NAMESPACE}.svc.cluster.local:8091
      dashboard:
        url: http://${K8S_MASTER_NODE_IP}:30094/repositories/user/${instanceId}
      manager:
        url: http://${K8S_MASTER_NODE_IP}:30092/scm
  keycloak:
    url: http://${KEYCLOAK_URL}/auth
    admin:
      id: ${KEYCLOAK_ADMIN_ID}
      password: ${KEYCLOAK_ADMIN_PASSWORD}
    realm:
      name: ${KEYCLOAK_CP_REALM}
    identity:
      provider:
        id: ${KEYCLOAK_IDENTITY_PROVIDER_ID}
    cluster:
      admin:
        group: ${KEYCLOAK_CLUSTER_ADMIN_GROUP}
        role: ${KEYCLOAK_CLUSTER_ADMIN_ROLE}
