# Default values for paas-ta-container-platform-webadmin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: container-platform-webadmin
  namespace: ${CONTAINER_PLATFORM_PORTAL_NAMESPACE}

spec:
  replicas: 1

image:
  registry: ${REPOSITORY_URL}
  project: ${REPOSITORY_PROJECT_NAME}
  name: paas-ta-container-platform-webadmin
  tags: ${IMAGE_TAGS}
  pullPolicy: ${IMAGE_PULL_POLICY}
  secret: ${IMAGE_PULL_SECRET}

service:
  type: ${SERVICE_TYPE}
  protocol: ${SERVICE_PROTOCOL}
  port: 8090
  targetPort: 8090
  nodePort: 32703

env:
  keycloak:
    url: "http://${KEYCLOAK_URL}"
    realm: "${KEYCLOAK_CP_REALM}"
    client:
      id: "${KEYCLOAK_CP_CLIENT_ID}"
      secret: "${KEYCLOAK_CP_CLIENT_SECRET}"
  cp:
    common:
      api:
        url: "http://${K8S_MASTER_NODE_IP}:32700"
    api:
      url: "http://${K8S_MASTER_NODE_IP}:32701"
