kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-pod-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-pod-provisioner
  replicas: {{ .Values.spec.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-pod-provisioner
    spec:
      serviceAccountName: nfs-pod-provisioner-sa # name of service account
      containers:
        - name: nfs-pod-provisioner
          image: {{ .Values.containers.image }}
          volumeMounts:
            - name: nfs-provisioner
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME # do not change
              value: paas-ta-container-platform-nfs-provisioner # SAME AS PROVISIONER NAME VALUE IN STORAGECLASS
            - name: NFS_SERVER # do not change
              value: {{ .Values.env.nfs.server.ip | quote }} # Ip of the NFS SERVER
            - name: NFS_PATH # do not change
              value: {{ .Values.env.nfs.path | quote }}  # path to nfs directory setup
      volumes:
        - name: nfs-provisioner # same as volumemouts name
          nfs:
            server: {{ .Values.env.nfs.server.ip | quote }}
            path: {{ .Values.env.nfs.path | quote }}